const words = [
  { word: "abacaxi", clue: "Fruta tropical com casca espinhosa" },
  { word: "avião", clue: "Meio de transporte aéreo" },
  { word: "bicicleta", clue: "Veículo de duas rodas movido por pedais" },
  { word: "computador", clue: "Máquina usada para processar dados" },
  { word: "dinossauro", clue: "Animal pré-histórico extinto" },
  { word: "elefante", clue: "Maior animal terrestre" },
  { word: "futebol", clue: "Esporte com bola muito popular no Brasil" },
  { word: "guitarra", clue: "Instrumento musical com cordas" },
  { word: "hipopótamo", clue: "Animal grande que vive em rios" },
  { word: "igreja", clue: "Lugar de culto religioso cristão" },
  { word: "janela", clue: "Abertura na parede para entrada de luz" },
  { word: "kiwi", clue: "Fruta verde por dentro e marrom por fora" },
  { word: "lampada", clue: "Dispositivo que emite luz artificial" },
  { word: "mamífero", clue: "Animal que amamenta seus filhotes" },
  { word: "nuvem", clue: "Conjunto de partículas de água no céu" },
  { word: "oceano", clue: "Grande massa de água salgada" },
  { word: "pinguim", clue: "Ave que vive no frio e não voa" },
  { word: "quadro", clue: "Objeto pendurado na parede, pode ser arte" },
  { word: "relógio", clue: "Objeto que marca o tempo" },
  { word: "sapato", clue: "Acessório usado nos pés" },
  { word: "tigre", clue: "Felino listrado de grande porte" },
  { word: "urso", clue: "Animal peludo, encontrado em regiões frias" },
  { word: "violino", clue: "Instrumento musical de cordas friccionadas" },
  { word: "xadrez", clue: "Jogo de tabuleiro com peças estratégicas" },
  { word: "zoológico", clue: "Lugar onde se abrigam animais para visitação" },
  { word: "arco-íris", clue: "Fenômeno com várias cores no céu" },
  { word: "bola", clue: "Objeto redondo usado em esportes" },
  { word: "cavalo", clue: "Animal usado para montaria" },
  { word: "dado", clue: "Pequeno cubo usado em jogos" },
  { word: "estrela", clue: "Corpo celeste que brilha no céu" },
  { word: "foca", clue: "Animal marinho que vive em águas geladas" },
  { word: "gelo", clue: "Água em estado sólido" },
  { word: "hotel", clue: "Lugar onde pessoas se hospedam" },
  { word: "ilha", clue: "Porção de terra cercada por água" },
  { word: "jornal", clue: "Publicação periódica com notícias" },
  { word: "lápis", clue: "Objeto usado para escrever ou desenhar" },
  { word: "montanha", clue: "Grande elevação natural do terreno" },
  { word: "navio", clue: "Grande embarcação para transporte marítimo" },
  { word: "óculos", clue: "Objeto usado para melhorar a visão" },
  { word: "pipoca", clue: "Alimento feito com milho aquecido" },
  { word: "quintal", clue: "Espaço aberto no fundo da casa" },
  { word: "rio", clue: "Curso natural de água doce" },
  { word: "sol", clue: "Estrela que ilumina a Terra" },
  { word: "tartaruga", clue: "Réptil de casco duro" },
  { word: "uva", clue: "Fruta pequena e redonda, usada para fazer vinho" },
  { word: "vulcão", clue: "Montanha que expele lava" },
  { word: "whisky", clue: "Bebida alcoólica destilada" },
  { word: "xícara", clue: "Recipiente para beber café ou chá" },
  { word: "yoga", clue: "Prática indiana de equilíbrio corporal e mental" },
  { word: "zangão", clue: "Inseto macho da abelha" }
];


export default function getWord() {
  const index = Math.floor(Math.random() * words.length);
  return words[index];
}
